AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'db/**/*'
    - 'tmp/**/*'
    - 'node_modules/**/*'

# 日本語のコメントを許可
Style/AsciiComments:
  Enabled: false

# Sinatraスタイルのコードに対応する設定
Style/ClassAndModuleChildren:
  Enabled: false

# DSLメソッドを許可
Metrics/BlockLength:
  Exclude:
    - '**/*.rb'

# メソッドの長さを緩和
Metrics/MethodLength:
  Max: 30

# 行の長さを緩和
Layout/LineLength:
  Max: 120

# クラスの長さを緩和
Metrics/ClassLength:
  Max: 150

# 複雑さを緩和
Metrics/CyclomaticComplexity:
  Max: 10

# ABCサイズを緩和
Metrics/AbcSize:
  Max: 30

# ドキュメントコメントを必須としない
Style/Documentation:
  Enabled: false

# 文字列のフリーズを強制しない
Style/FrozenStringLiteralComment:
  Enabled: false

# シングルクォートとダブルクォートの使い分けを緩和
Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

# トレイリングコンマを許可
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

# グローバル変数の使用を許可（Sinatraでは一般的）
Style/GlobalVars:
  Enabled: false

# rescueの例外指定を緩和
Style/RescueStandardError:
  EnforcedStyle: implicit
