source 'https://rubygems.org'

gem 'dotenv'
gem 'faraday'
gem 'json'
gem 'rack', '~> 2.2.8'
gem 'sinatra'
gem 'sinatra-websocket'
gem 'thin', '~> 1.8.0'

group :development do
  gem 'rubocop', require: false
end
